apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mariadb
  annotations:
    robin.io/replication: "2"
    robin.io/faultdomain: "host"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: general
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS employees;
    USE employees; CREATE TABLE employees (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100), age INT, department VARCHAR(50), salary DECIMAL(10,2), hire_date DATE);
    USE employees; INSERT INTO employees (name, age, department, salary, hire_date) VALUES ('John Doe', 30, 'HR', 50000.00, '2022-05-10'), ('Jane Smith', 28, 'IT', 70000.00, '2021-09-15'), ('Alice Johnson', 35, 'Finance', 80000.00, '2019-11-20'), ('Bob Williams', 40, 'Marketing', 60000.00, '2018-07-03'), ('Charlie Brown', 25, 'IT', 55000.00, '2023-01-10');
    USE employees; INSERT INTO employees (name, age, department, salary, hire_date) VALUES ('John Doe', 30, 'HR', 50000.00, '2022-05-10'), ('Jane Smith', 28, 'IT', 70000.00, '2021-09-15'), ('Alice Johnson', 35, 'Finance', 80000.00, '2019-11-20'), ('Bob Williams', 40, 'Marketing', 60000.00, '2018-07-03'), ('Charlie Brown', 25, 'IT', 55000.00, '2023-01-10');
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root123
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mariadb-storage
          - mountPath: /docker-entrypoint-initdb.d
            name: init-scripts
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: pvc-mariadb
      - name: init-scripts
        configMap:
          name: mariadb-init
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
apiVersion: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: public/apache:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: mariadb
            - name: DB_NAME
              value: employees
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: root123
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-frontend
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31080

