apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mariadb
  annotations:
    robin.io/replication: "2"
    robin.io/faultdomain: "host"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root123
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mariadb-storage
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: pvc-mariadb
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
apiVersion: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: public/apache:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: mariadb
            - name: DB_NAME
              value: employees
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: root123
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-frontend
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

